# Generated by Django 3.1.4 on 2020-12-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fav_books', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='fav_books.user'),
        ),
        migrations.AlterField(
            model_name='book',
            name='user_likes',
            field=models.ManyToManyField(related_name='fav_books', to='fav_books.User'),
        ),
    ]
